name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace secrets
        run: |
          sed -i "s/%%PASSWORD%%/${{ secrets.PASSWORD }}/g" password.js
          sed -i "s/%%API_KEY%%/${{ secrets.API_KEY }}/g" timeline.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # The directory to publish to GitHub Pages
